CREATE DATABASE Grocery_store;
USE Grocery_store;

-- 1. Supplier
CREATE TABLE supplier (
  sup_id TINYINT PRIMARY KEY,
  sup_name VARCHAR(255),
  address TEXT
);

-- 2. Categories
CREATE TABLE categories (
  cat_id TINYINT PRIMARY KEY,
  cat_name VARCHAR(255)
);

-- 3. Employees
CREATE TABLE employees (
  emp_id TINYINT PRIMARY KEY,
  emp_name VARCHAR(255),
  hire_date VARCHAR(255)
);

-- 4. Customers
CREATE TABLE customers (
  cust_id SMALLINT PRIMARY KEY,
  cust_name VARCHAR(255),
  address TEXT
);

-- 5. Products
CREATE TABLE products (
  prod_id TINYINT PRIMARY KEY,
  prod_name VARCHAR(255),
  sup_id TINYINT,
  cat_id TINYINT,
  price DECIMAL(10,2),
  FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders
CREATE TABLE orders (
  ord_id SMALLINT PRIMARY KEY,
  cust_id SMALLINT,
  emp_id TINYINT,
  order_date VARCHAR(255),
  FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details
CREATE TABLE order_details (
  ord_detID SMALLINT PRIMARY KEY,
  ord_id SMALLINT,
  prod_id TINYINT,
  quantity TINYINT,
  each_price DECIMAL(10,2),
  total_price DECIMAL(10,2),
  FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (prod_id) REFERENCES products(prod_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM supplier LIMIT 5;
SELECT * FROM products LIMIT 5;
SELECT * FROM orders LIMIT 5;
SELECT * FROM order_details LIMIT 5;

UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y');
ALTER TABLE orders
MODIFY order_date DATE;


--  Customer Insights
-- number of unique customers have placed orders
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- The customers who placed the highest number of orders
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM orders o
JOIN customers c ON o.cust_id = c.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC
LIMIT 5;

-- The total and average purchase value per customer
SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC;

-- The Top 5 customers by total purchase amount
SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;


-- Product Performance
-- How many products exist in each category
SELECT c.cat_id, c.cat_name,
       COUNT(p.prod_id) AS product_count
FROM categories c
LEFT JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name;

--  Average price of products by category
SELECT c.cat_name,
       AVG(p.price) AS avg_price
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

--  Product with highest total sales volume (by quantity)
SELECT p.prod_id, p.prod_name,
       SUM(od.quantity) AS total_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity DESC
LIMIT 1;

--  Total revenue generated by each product
SELECT p.prod_id, p.prod_name,
       SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- Product sales by category and supplier (quantity)
SELECT c.cat_name,
       s.sup_name,
       SUM(od.quantity) AS total_quantity
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY c.cat_name, total_quantity DESC;


-- Sales and Order Trends 
--  Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;

--  Average value per order
SELECT o.ord_id,
       SUM(od.total_price) AS order_total
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.ord_id;

--  Date with most orders
SELECT order_date,
       COUNT(*) AS orders_placed
FROM orders
GROUP BY order_date
ORDER BY orders_placed DESC
LIMIT 1;

--  Monthly trends in order volume and revenue
SELECT YEAR(o.order_date)  AS order_year,
       MONTH(o.order_date) AS order_month,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY order_year, order_month
ORDER BY order_year, order_month;

--  Weekday vs weekend patterns
SELECT CASE
         WHEN WEEKDAY(o.order_date) IN (5, 6) THEN 'Weekend'
         ELSE 'Weekday'
       END AS day_type,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS total_revenue,
       AVG(od.total_price) AS avg_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_type;


-- Supplier Contribution
-- Number of suppliers
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- Supplier providing the most products
SELECT s.sup_id, s.sup_name,
       COUNT(p.prod_id) AS products_provided
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY products_provided DESC;

-- Average price of products from each supplier
SELECT s.sup_id, s.sup_name,
       AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_price DESC;

-- Suppliers contributing most to sales (by revenue)
SELECT s.sup_id, s.sup_name,
       SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;


-- Employee Performance
-- How many employees processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_with_orders
FROM orders;

-- Employees who handled the most orders
SELECT e.emp_id, e.emp_name,
       COUNT(o.ord_id) AS orders_processed
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY orders_processed DESC;

-- Total sales value processed by each employee
SELECT e.emp_id, e.emp_name,
       SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales DESC;

-- Average order value handled per employee
SELECT e.emp_id, e.emp_name,
       AVG(order_total) AS avg_order_value
FROM (
    SELECT o.emp_id, o.ord_id,
           SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) t
JOIN employees e ON t.emp_id = e.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;


-- Order Details Deep Dive
-- Relationship between quantity and total price (raw view)
SELECT prod_id, quantity, each_price, total_price
FROM order_details;

-- Average quantity ordered per product
SELECT p.prod_id, p.prod_name,
       AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity DESC;

-- Unit price variation across products and orders
SELECT od.prod_id, p.prod_name, od.ord_id,
       MIN(od.each_price) AS min_unit_price,
       MAX(od.each_price) AS max_unit_price
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
GROUP BY od.prod_id, p.prod_name, od.ord_id
ORDER BY p.prod_name, od.ord_id;

-- Products most frequently purchased in bulk (quantity >= 5)
SELECT p.prod_name,
       COUNT(*) AS bulk_purchase_count
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
WHERE od.quantity >= 5
GROUP BY p.prod_name
ORDER BY bulk_purchase_count DESC;